spring:
  datasource:
    url: jdbc:sqlite:./data/devdb.sqlite
    driver-class-name: org.sqlite.JDBC
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration/sqlite


